# Generated by Django 4.1 on 2022-09-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_project_options_alter_project_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
